apiVersion: v1
kind: Service
metadata:
  name: ilyas-wordpress-mysql
  labels:
    app: ilyas-wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: ilyas-wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: ilyas-wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilyas-wordpress-mysql
  labels:
    app: ilyas-wordpress
spec:
  selector:
    matchLabels:
      app: ilyas-wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ilyas-wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
