apiVersion: v1
kind: Service
metadata:
  name: ilyas-wordpress
  labels:
    app: ilyas-wordpress
spec:
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 80
  selector:
    app: ilyas-wordpress
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: ilyas-wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilyas-wordpress
  labels:
    app: ilyas-wordpress
spec:
  selector:
    matchLabels:
      app: ilyas-wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ilyas-wordpress
    spec:
      containers:
      - image: wordpress:latest
        name: ilyas-wordpress
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
        env:
        - name: WORDPRESS_DB_HOST
          value: ilyas-wordpress-mysql.default.svc.cluster.local
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WORDPRESS_DB_USER
          value: wordpress
        ports:
        - containerPort: 80
          name: ilyas-wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
